Repository MyNihongo/MudBlazor.Markdown, pull requests merged in 2021-08, with the labels that each got.

#5 handle a new-line character in tables
  .github/workflows/ci-build.yml
  README.md
  samples/MudBlazor.Markdown.Core/sample.md
  samples/Server/Pages/Index.razor
  src/MudBlazor.Markdown/MudBlazor.Markdown.csproj
  src/MudBlazor.Markdown/MudMarkdown.razor.cs
  src/MudBlazor.Markdown/Resources/MudBlazor.Markdown.css
  tests/MudBlazor.Markdown.Tests/MudMarkdownTestCases.cs
  tests/MudBlazor.Markdown.Tests/MudMarkdownTests.cs
  tests/MudBlazor.Markdown.Tests/MudMarkdownTestsBase.cs
  tests/MudBlazor.Markdown.Tests/TestCommand.cs
Labels: enhancement

#6 fix the release ci
  .github/workflows/ci-build.yml
Labels: ci

#7 fix NuGet push on release
  .github/workflows/ci-build.yml
Labels: ci

#8 publish NuGet via artifacts
  .github/workflows/ci-build.yml
Labels: ci

#9 start the release phase if its tag is present
  .github/workflows/ci-build.yml
Labels: ci

#10 publish NuGet to GitHub packages
  .github/workflows/ci-build.yml
Labels: ci

#12 add the dependabot
  .github/dependabot.yaml
  samples/MudBlazor.Markdown.Samples.sln
  samples/Server/MudBlazor.Markdown.Server.csproj
  samples/Server/MudBlazor.Markdown.Server.sln
  samples/WebAssembly/MudBlazor.Markdown.Wasm.csproj
  src/MudBlazor.Markdown/MudBlazor.Markdown.csproj
  tests/MudBlazor.Markdown.Tests/MudBlazor.Markdown.Tests.csproj
Labels: ci

#14 remove package.json files from NuGet content
  MudBlazor.Markdown.sln
  src/MudBlazor.Markdown/MudBlazor.Markdown.csproj
Labels: bug

#15 Run npm script instead of global script
  src/MudBlazor.Markdown/MudBlazor.Markdown.csproj
  src/MudBlazor.Markdown/package.json
Labels: good first issue

#17 use Optional parameters in tests
  tests/MudBlazor.Markdown.Tests/ComponentParameterCollectionBuilderEx.cs
  tests/MudBlazor.Markdown.Tests/MudBlazor.Markdown.Tests.csproj
  tests/MudBlazor.Markdown.Tests/MudMarkdownTests.cs
  tests/MudBlazor.Markdown.Tests/MudMarkdownTestsBase.cs
Labels: enhancement

#19 link improvements
  src/MudBlazor.Markdown/Extensions/EmphasisInlineEx.cs
  src/MudBlazor.Markdown/Extensions/HeadingBlockEx.cs
  src/MudBlazor.Markdown/MudMarkdown.razor.cs
  src/MudBlazor.Markdown/Resources/MudBlazor.Markdown.css
  tests/MudBlazor.Markdown.Tests/Extensions/HeadingBlockExTests/BuildIdStringShould.cs
  tests/MudBlazor.Markdown.Tests/Extensions/HeadingBlockExTests/BuildIdStringShouldTestsBase.cs
  tests/MudBlazor.Markdown.Tests/MudBlazor.Markdown.Tests.csproj
  tests/MudBlazor.Markdown.Tests/MudMarkdownTestCases.cs
  tests/MudBlazor.Markdown.Tests/MudMarkdownTests.cs
Labels: enhancement

#22 implement navigation to headers
  README.md
  samples/MudBlazor.Markdown.Core/MudBlazor.Markdown.Core.csproj
  samples/MudBlazor.Markdown.Core/Services/Interfaces/IMarkdownService.cs
  samples/MudBlazor.Markdown.Core/Services/MarkdownService.cs
  samples/MudBlazor.Markdown.Core/sample-enderal.md
  samples/Server/Pages/Index.razor
  samples/Server/Pages/_Host.cshtml
  samples/WebAssembly/Pages/Index.razor
  samples/WebAssembly/wwwroot/index.html
  src/MudBlazor.Markdown/Extensions/HeadingBlockEx.cs
  src/MudBlazor.Markdown/MudMarkdown.razor.cs
  src/MudBlazor.Markdown/Resources/MudBlazor.Markdown.css
  src/MudBlazor.Markdown/Resources/MudBlazor.Markdown.js
  src/MudBlazor.Markdown/gulpfile.js
  src/MudBlazor.Markdown/package-lock.json
  src/MudBlazor.Markdown/package.json
  tests/MudBlazor.Markdown.Tests/MudBlazor.Markdown.Tests.csproj
  tests/MudBlazor.Markdown.Tests/MudMarkdownTests.cs
  tests/MudBlazor.Markdown.Tests/MudMarkdownTestsBase.cs
  tests/MudBlazor.Markdown.Tests/MudMarkdownTestsLinkNav.cs
  tests/MudBlazor.Markdown.Tests/Services/TestNavigationManager.cs
Labels: enhancement

#24 bump to 0.0.3
  samples/MudBlazor.Markdown.Core/MudBlazor.Markdown.Core.csproj
  samples/Server/MudBlazor.Markdown.Server.csproj
  src/MudBlazor.Markdown/MudBlazor.Markdown.csproj
Labels: release

#30 override some parameters with a func parameter
  samples/Server/Pages/Index.razor
  src/MudBlazor.Markdown/MudMarkdown.razor.cs
  tests/MudBlazor.Markdown.Tests/MarkdownComponentTests/MarkdownComponentHeadersShould.cs
  tests/MudBlazor.Markdown.Tests/MarkdownComponentTests/MarkdownComponentLinksShould.cs
  tests/MudBlazor.Markdown.Tests/MarkdownComponentTests/MarkdownComponentShould.cs
  tests/MudBlazor.Markdown.Tests/MarkdownComponentTests/MarkdownComponentTestsBase.cs
  tests/MudBlazor.Markdown.Tests/UrlOverrideTests/MarkdownComponentShould.cs
  tests/MudBlazor.Markdown.Tests/UrlOverrideTests/UrlOverrideTestsBase.cs
Labels: enhancement

#31 Release/version 0.0.4
  README.md
  src/MudBlazor.Markdown/MudBlazor.Markdown.csproj
Labels: release
